# Spring Boot application name

spring.application.name=siliconApplication

 

# DataSource configuration

spring.datasource.url=jdbc:mysql://localhost:3306/silicon?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC

spring.datasource.username=root

spring.datasource.password=Apanda@2005
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

 

# Hibernate JPA settings

spring.jpa.hibernate.ddl-auto=update          

 # Can be: none | validate | update | create | create-drop

spring.jpa.show-sql=true                      

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

spring.jpa.properties.hibernate.format_sql=true # Pretty print SQL

spring.jpa.open-in-view=false                  

 

# Optional: Enable SQL comment generation

spring.jpa.properties.hibernate.use_sql_comments=true


